### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by paleobotany** [ropensci/phylodiv#1]
@sckott thanks for building this package

I cannot install it, though; it seems that as_data_frame no longer belongs to tidytree.

<Error: object ‘as_data_frame’ is not exported by 'namespace:tidytree'
Execution halted>

**Comment by sckott** [comment]
thanks for opening the issue. I'll have a look. I haven't touched this in a while so I am not surprised it doesn't quite work

**Comment by sckott** [comment]
let me know if it works for you now
